name: Deploy Infrastructure

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: b4e68346-f510-4146-9ec3-672e008c81ae
          tenant-id: 6c560666-4010-488d-90f9-57963cc5a7bf
          subscription-id: 48ab377d-9bc4-4f07-9ac8-fa30fbaab28b

      - name: Deploy subscription resources
        run: |
          az deployment sub create \
            --location mexicocentral \
            --template-file subscription.bicep \
            --parameters @environments/test/subscription.parameters.json

      - name: Deploy resource group resources
        run: |
          az deployment group create \
            --resource-group rg-stackoverflow2010-test-mexicocentral \
            --template-file main.bicep \
            --parameters @environments/test/main.parameters.json